<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>951c08ac-1f07-46b4-9590-47fd6b3af189</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cesardd.Core\Cesardd.Core.csproj" />
    <ProjectReference Include="..\Cesardd.Infrastructure\Cesardd.Infrastructure.csproj" />
    <ProjectReference Include="..\Cesardd.Shared\Cesardd.Shared.csproj" />
  </ItemGroup>

</Project>
